name: "PR Checks"
on: push

jobs:
    test:
        runs-on: ubuntu-latest
        name: Action Test
        steps:
            - uses: actions/checkout@v1

            - name: "Install Dependencies"
              run: npm install

            - name: "Build the package"
              run: npm run build

            - uses: ./
              with:
                username: ${{ secrets.SAUCE_USERNAME }}
                accessKey: ${{ secrets.SAUCE_ACCESS_KEY }}
                tunnelName: github-action-tunnel
                tunnelPool: true
                configFile: ${{ github.workspace }}/sc-configuration/config.yaml
                directDomains: domain#

            - name: "Run Test"
              run: npm run test
              env:
                SAUCE_USERNAME: ${{ secrets.SAUCE_USERNAME }}
                SAUCE_ACCESS_KEY: ${{ secrets.SAUCE_ACCESS_KEY }}

            - uses: actions/upload-artifact@v2
              if: ${{ failure() }}
              with:
                name: sauce-connect-log
                path: ${{ env.SAUCE_CONNECT_DIR_IN_HOST }}/sauce-connect.log
